name: Angular CI

on:
  push:
    branches:
      - main

jobs:
  build-angular-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Start Gulp App
        run: npm start
